//
//  main.cpp
//  problem12
//
//  Created by Zack Fanning on 12/9/15.
//  Copyright © 2015 Zackluckyf. All rights reserved.
//

/*
 The sequence of triangle numbers is generated by adding the natural numbers. 
 So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 The first ten terms would be:
 
 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 
 Let us list the factors of the first seven triangle numbers:
 
  1: 1
  3: 1,3
  6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.
 
 What is the value of the first triangle number to have over five hundred divisors?
*/

#include <iostream>
#include <cmath>

int main(int argc, const char * argv[])
{
    int count(0);
    long long number(0);
    for (int i = 1; i < 13000; i+= 2)
    {
        number = i * (i + 1) / 2;
        count = 0;
        {
        for (int j = 1; j <= sqrt(number); j++)
        {
            if (number % j == 0)
            {
                count+=2;
            }
            if (count > 500)
            {
                std::cout << number << std::endl;
            }
        }
        }
    }
   
    return 0;
}
